services:
  mongodb:
    image: mongo:latest
    container_name: projet-fil-rouge-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env


volumes:
  mongodb_data: